/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccountRouteImport } from './routes/account'
import { Route as HelpRouteImport } from './routes/help'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AccountIndexRouteImport } from './routes/account.index'
import { Route as AccountMySavedEventsRouteImport } from './routes/account.my-saved-events'
import { Route as AccountMyTicketsRouteImport } from './routes/account.my-tickets'
import { Route as EventsEventSlugRouteImport } from './routes/events.$eventSlug'
import { Route as EventsKenyaRouteImport } from './routes/events.kenya'
import { Route as HelpIndexRouteImport } from './routes/help.index'
import { Route as HelpTicketBuyersRouteImport } from './routes/help.ticket-buyers'
import { Route as LegalPrivacyRouteImport } from './routes/legal.privacy'
import { Route as LegalTermsRouteImport } from './routes/legal.terms'
import { Route as AccountEarnCommissionReferralsRouteImport } from './routes/account.earn-commission.referrals'
import { Route as AccountEventNewRouteImport } from './routes/account.event.new'
import { Route as HelpArticlesArticleSlugRouteImport } from './routes/help.articles.$articleSlug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountRoute,
} as any)
const AccountMySavedEventsRoute = AccountMySavedEventsRouteImport.update({
  id: '/my-saved-events',
  path: '/my-saved-events',
  getParentRoute: () => AccountRoute,
} as any)
const AccountMyTicketsRoute = AccountMyTicketsRouteImport.update({
  id: '/my-tickets',
  path: '/my-tickets',
  getParentRoute: () => AccountRoute,
} as any)
const EventsEventSlugRoute = EventsEventSlugRouteImport.update({
  id: '/events/$eventSlug',
  path: '/events/$eventSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsKenyaRoute = EventsKenyaRouteImport.update({
  id: '/events/kenya',
  path: '/events/kenya',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpIndexRoute = HelpIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HelpRoute,
} as any)
const HelpTicketBuyersRoute = HelpTicketBuyersRouteImport.update({
  id: '/ticket-buyers',
  path: '/ticket-buyers',
  getParentRoute: () => HelpRoute,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountEarnCommissionReferralsRoute =
  AccountEarnCommissionReferralsRouteImport.update({
    id: '/earn-commission/referrals',
    path: '/earn-commission/referrals',
    getParentRoute: () => AccountRoute,
  } as any)
const AccountEventNewRoute = AccountEventNewRouteImport.update({
  id: '/event/new',
  path: '/event/new',
  getParentRoute: () => AccountRoute,
} as any)
const HelpArticlesArticleSlugRoute = HelpArticlesArticleSlugRouteImport.update({
  id: '/articles/$articleSlug',
  path: '/articles/$articleSlug',
  getParentRoute: () => HelpRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRouteWithChildren
  '/help': typeof HelpRouteWithChildren
  '/login': typeof LoginRoute
  '/account/my-saved-events': typeof AccountMySavedEventsRoute
  '/account/my-tickets': typeof AccountMyTicketsRoute
  '/events/$eventSlug': typeof EventsEventSlugRoute
  '/events/kenya': typeof EventsKenyaRoute
  '/help/ticket-buyers': typeof HelpTicketBuyersRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/account/': typeof AccountIndexRoute
  '/help/': typeof HelpIndexRoute
  '/account/earn-commission/referrals': typeof AccountEarnCommissionReferralsRoute
  '/account/event/new': typeof AccountEventNewRoute
  '/help/articles/$articleSlug': typeof HelpArticlesArticleSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/account/my-saved-events': typeof AccountMySavedEventsRoute
  '/account/my-tickets': typeof AccountMyTicketsRoute
  '/events/$eventSlug': typeof EventsEventSlugRoute
  '/events/kenya': typeof EventsKenyaRoute
  '/help/ticket-buyers': typeof HelpTicketBuyersRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/account': typeof AccountIndexRoute
  '/help': typeof HelpIndexRoute
  '/account/earn-commission/referrals': typeof AccountEarnCommissionReferralsRoute
  '/account/event/new': typeof AccountEventNewRoute
  '/help/articles/$articleSlug': typeof HelpArticlesArticleSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRouteWithChildren
  '/help': typeof HelpRouteWithChildren
  '/login': typeof LoginRoute
  '/account/my-saved-events': typeof AccountMySavedEventsRoute
  '/account/my-tickets': typeof AccountMyTicketsRoute
  '/events/$eventSlug': typeof EventsEventSlugRoute
  '/events/kenya': typeof EventsKenyaRoute
  '/help/ticket-buyers': typeof HelpTicketBuyersRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/account/': typeof AccountIndexRoute
  '/help/': typeof HelpIndexRoute
  '/account/earn-commission/referrals': typeof AccountEarnCommissionReferralsRoute
  '/account/event/new': typeof AccountEventNewRoute
  '/help/articles/$articleSlug': typeof HelpArticlesArticleSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/help'
    | '/login'
    | '/account/my-saved-events'
    | '/account/my-tickets'
    | '/events/$eventSlug'
    | '/events/kenya'
    | '/help/ticket-buyers'
    | '/legal/privacy'
    | '/legal/terms'
    | '/account/'
    | '/help/'
    | '/account/earn-commission/referrals'
    | '/account/event/new'
    | '/help/articles/$articleSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/login'
    | '/account/my-saved-events'
    | '/account/my-tickets'
    | '/events/$eventSlug'
    | '/events/kenya'
    | '/help/ticket-buyers'
    | '/legal/privacy'
    | '/legal/terms'
    | '/account'
    | '/help'
    | '/account/earn-commission/referrals'
    | '/account/event/new'
    | '/help/articles/$articleSlug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/help'
    | '/login'
    | '/account/my-saved-events'
    | '/account/my-tickets'
    | '/events/$eventSlug'
    | '/events/kenya'
    | '/help/ticket-buyers'
    | '/legal/privacy'
    | '/legal/terms'
    | '/account/'
    | '/help/'
    | '/account/earn-commission/referrals'
    | '/account/event/new'
    | '/help/articles/$articleSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRouteWithChildren
  HelpRoute: typeof HelpRouteWithChildren
  LoginRoute: typeof LoginRoute
  EventsEventSlugRoute: typeof EventsEventSlugRoute
  EventsKenyaRoute: typeof EventsKenyaRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalTermsRoute: typeof LegalTermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/my-saved-events': {
      id: '/account/my-saved-events'
      path: '/my-saved-events'
      fullPath: '/account/my-saved-events'
      preLoaderRoute: typeof AccountMySavedEventsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/my-tickets': {
      id: '/account/my-tickets'
      path: '/my-tickets'
      fullPath: '/account/my-tickets'
      preLoaderRoute: typeof AccountMyTicketsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/events/$eventSlug': {
      id: '/events/$eventSlug'
      path: '/events/$eventSlug'
      fullPath: '/events/$eventSlug'
      preLoaderRoute: typeof EventsEventSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/kenya': {
      id: '/events/kenya'
      path: '/events/kenya'
      fullPath: '/events/kenya'
      preLoaderRoute: typeof EventsKenyaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help/': {
      id: '/help/'
      path: '/'
      fullPath: '/help/'
      preLoaderRoute: typeof HelpIndexRouteImport
      parentRoute: typeof HelpRoute
    }
    '/help/ticket-buyers': {
      id: '/help/ticket-buyers'
      path: '/ticket-buyers'
      fullPath: '/help/ticket-buyers'
      preLoaderRoute: typeof HelpTicketBuyersRouteImport
      parentRoute: typeof HelpRoute
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/earn-commission/referrals': {
      id: '/account/earn-commission/referrals'
      path: '/earn-commission/referrals'
      fullPath: '/account/earn-commission/referrals'
      preLoaderRoute: typeof AccountEarnCommissionReferralsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/event/new': {
      id: '/account/event/new'
      path: '/event/new'
      fullPath: '/account/event/new'
      preLoaderRoute: typeof AccountEventNewRouteImport
      parentRoute: typeof AccountRoute
    }
    '/help/articles/$articleSlug': {
      id: '/help/articles/$articleSlug'
      path: '/articles/$articleSlug'
      fullPath: '/help/articles/$articleSlug'
      preLoaderRoute: typeof HelpArticlesArticleSlugRouteImport
      parentRoute: typeof HelpRoute
    }
  }
}

interface AccountRouteChildren {
  AccountMySavedEventsRoute: typeof AccountMySavedEventsRoute
  AccountMyTicketsRoute: typeof AccountMyTicketsRoute
  AccountIndexRoute: typeof AccountIndexRoute
  AccountEarnCommissionReferralsRoute: typeof AccountEarnCommissionReferralsRoute
  AccountEventNewRoute: typeof AccountEventNewRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountMySavedEventsRoute: AccountMySavedEventsRoute,
  AccountMyTicketsRoute: AccountMyTicketsRoute,
  AccountIndexRoute: AccountIndexRoute,
  AccountEarnCommissionReferralsRoute: AccountEarnCommissionReferralsRoute,
  AccountEventNewRoute: AccountEventNewRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

interface HelpRouteChildren {
  HelpTicketBuyersRoute: typeof HelpTicketBuyersRoute
  HelpIndexRoute: typeof HelpIndexRoute
  HelpArticlesArticleSlugRoute: typeof HelpArticlesArticleSlugRoute
}

const HelpRouteChildren: HelpRouteChildren = {
  HelpTicketBuyersRoute: HelpTicketBuyersRoute,
  HelpIndexRoute: HelpIndexRoute,
  HelpArticlesArticleSlugRoute: HelpArticlesArticleSlugRoute,
}

const HelpRouteWithChildren = HelpRoute._addFileChildren(HelpRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRouteWithChildren,
  HelpRoute: HelpRouteWithChildren,
  LoginRoute: LoginRoute,
  EventsEventSlugRoute: EventsEventSlugRoute,
  EventsKenyaRoute: EventsKenyaRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalTermsRoute: LegalTermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
